url: https://opensource4pa.com
baseurl: /

# Site settings
title: Open Source for Public Administrations
email: info@opensource4pa.com
description: "Promoting the use, development and spreading of open source software in public administrations"


# Team names, titles and social links
people:
- name: J. V. Garcia
  pic: 1
  position: Lead Developer
  social:
    - title: github
      url: #
    - title: linkedin
      url: #
    - title: stack-overflow
      url: #

- name: Rotzel Huerta
  pic: 2
  position: Lead Marketer
  social:
    - title: github
      url: #
    - title: outlook
      url: #
    - title: linkedin
      url: #

- name: Pura G. M.
  pic: 3
  position: Lead Administrative manager
  social:
    - title: github
      url: #
    - title: outlook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/open-pol
  - title: linkedin
    url: https://www.linkedin.com/in/josevtegarcia/
  - title: stack-overflow
    url: https://stackoverflow.com/users/12798097/jose-v-garcia
  - title: github
    url: https://github.com/openpol-org/OpenPol

# Postal address (add as many lines as necessary)
address:
  - line: Calle Consuelo 20 Bajo D
  - line: 46011, Valencia, Spain

# Build settings
markdown: kramdown
permalink: pretty